### ISSUE TITLE
Discontinued services

### ISSUE THREAD

**Issue by Dumk0** [florianv/exchanger#43] opened 2018-04-12 06:43 UTC
Hello and thank You for such a handful piece of software.

Unfortunately, some of supported exchange rate services are discontinued:
Google, Yahoo, *Fixer

Fixer is still operating but they will close the old API soon.
Good news is that Fixer still offers free (limited) and also paid access.
Read more about it here https://github.com/fixerAPI/fixer#readme

**Suggestions:**
1. add notice in the project about deprecated services like Yahoo and Google
2. add similar notice in Swap project as well
3. upgrade Fixer service client to support new version of API with access token

**Comment by dannyweeks** [comment] 2018-04-15 19:00
Google is still working for me. The old finance.google was changed out for a straight search or what leads you the believe Google has discontinued?

**Comment by florianv** [comment] 2018-04-16 06:35
@dannyweeks Yes Google is still working but it was changed to a straight search because they discontinued the service we were using.

@Dumk0 Could you please go ahead and send a PR for this ? Thanks!

**Comment by florianv** [comment] 2018-04-16 15:33
@ddinchev Yahoo was already deprecated with a @deprecated comment!

**Comment by florianv** [comment] 2018-04-17 06:30
I am closing this, since it will be considered in version `1.0.0` of Exchanger

**Closed by florianv** 2018-04-17 06:30 UTC

**Comment by driade** [comment] 2018-04-18 22:50
@florianv Google stoped working for me since a few minutes ago, if I run the code from the server (UK) . If I run it from my machine (ES) it still seems to work. Will check.

**Comment by florianv** [comment] 2018-04-19 06:36
@driade Thanks for this! It looks like Google is not reliable anymore

**Comment by driade** [comment] 2018-04-21 09:58
@florianv False alarm. I can confirm at this moment it's working both locally and on the server. My website extracts the values for many currencies from EUR. MXN, GBP, USD, ARS, COP, CLP, PEN, UYU and BRL.

This is an screenshot from my control panel

<img width="622" alt="captura de pantalla 2018-04-21 a las 11 57 01" src="https://user-images.githubusercontent.com/5692232/39082915-260d8aa8-455b-11e8-96c4-81cb6cf662fa.png">

**Comment by jacobtylerdavis** [comment] 2018-04-21 11:48
@deride It may still be very unreliable.  For example, after a certain number of queries Google will start requiring CAPTCHA.
